### ISSUE TITLE
Remote work the new normal?

### ISSUE THREAD

**Issue by jonrohan** [jasoncwarner/ama#14]
With more companies announcing remote policies because of the pandemic, what's your take on if this is permanent? I'm curious if we're seeing the dawn of a new era of all tech companies working remote, or if it's mostly media sensationalism.

**Comment by jasoncwarner** [comment]
Yes. Forward thinking companies are looking at remote-first w/ HQ and satellite offices for people to go to if they want social connections (not needed if they don't want it). 

That said, there will always be a set of folks against this b/c *they* can't work this way. When those folks are in positions of power those companies will be held back. Right now it is all back half of bell curve companies and some contrarian high-tech companies with oddly rigid thinking. 

We will see more and more companies adopt this. We'll also see several double down on "SF only" still as some contrarian badge for some period of time. Though in time remote first will win out.

**Comment by jasoncwarner** [comment]
I should add a few caveats. 

1. remote != 'never get together'. 
2. hardware companies are different
3. tech companies are the likely the norm for people reading this and I'm specifically addressing tech....but a lot of the world can't do what we do. 

Last caveat. The tools are going to get better. When I started remote the tools were literally IRC and Skype (I have no idea how Skype ever was a viable product, it was such a terrible tool no one used it). Today we have GitHub, Zoom, Teams/Slack, Loom and a bunch of new tools starting every day. The tools are going to get better and MUCH better quickly. This will make it that much better.
